export default {
  WRAPPER_WIDTH: 800,
  WRAPPER_HEIGHT: 200,
  WRAPPER_PADDING: 20,
  WRAPPER_FONT_SIZE: 30,
  GITHUB_ICON: {
    WIDTH: 44,
    HEIGHT: 44,
    SHAPE_REDERING: 'crispEdges',
  },
};
