const ROOM = {
  FIELD_ROW: 8,
  FIELD_COLUMN: 16,
  SECOND: 1000, // 1s
  TIME_LIMIT: 60, // 60s
  MAX_USER: 20,
  MAX_ROUND: 10,
};

const DIRECTION = {
  DOWN: 0,
  LEFT: 1,
  RIGHT: 2,
  UP: 3,
};

const FIELD = {
  O_START: 0,
  O_END: ROOM.FIELD_COLUMN / 2,
  X_START: ROOM.FIELD_COLUMN / 2,
  X_END: ROOM.FIELD_COLUMN,
};

export { ROOM, DIRECTION, FIELD };
